stages:
  - test
  - build
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

.docker_setup: &docker_setup
  services:
    - docker:dind
  image: docker:latest
  before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_USER $CI_REGISTRY

test:
  stage: test
  script:
    - docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit
  only:
    - merge_requests

build:
  stage: build
  <<: *docker_setup
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  only:
    - main
    - develop

deploy_staging:
  stage: deploy
  <<: *docker_setup
  script:
    - docker-compose -f docker-compose.staging.yml pull
    - docker-compose -f docker-compose.staging.yml up -d
  environment:
    name: staging
  only:
    - deveelop

deploy_production:
  stage: deploy
  <<: *docker_setup
  script:
    - docker-compose -f docker-compose.production.yml pull
    - docker-compose -f docker-compose.production.yml up -d
  environment:
    name: production
  when: manual
  only:
    - main