version: "3.3"

services:
  mariadb:
    container_name: mariadb
    restart: always
    image: mariadb:10.3
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${DATABASE_NAME:-devdb}
    volumes:
      - mariadb:/var/lib/mysql
      - ./dumps:/dumps
    ports:
      - "${DATABASE_PORT:-3306}:3306"
    networks:
      - backend
    
  postgres:
    container_name: postgres
    restart: always
    image: postgres:16.3-alpine
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=${POSTGRES_DATABASE_NAME:-postgresdb}
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./dumps:/dumps
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - backend

  redis:
    image: redis:5-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  traefik:
    container_name: "traefik"
    image: "traefik:1.7.20"
    restart: "always"
    command: --api --docker=true
    ports:
      - "80:80"
      - "8081:8080"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./traefik:/etc/traefik
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:traefik.localhost"
      - "traefik.port=8080"
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=root
      - UPLOAD_LIMIT=512M
    volumes:
      - ./config/phpmyadmin/phpmyadmin.ini:/usr/local/etc/php/conf.d/phpmyadmin.ini
    networks:
      - backend
    depends_on:
      - mariadb
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:phpmyadmin.localhost"
      - "traefik.port=80"

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:pgadmin.localhost"
      - "traefik.port=80"

  apache-php:
    image: php:${PHP_VERSION:-8.2}-apache
    volumes:
      - ${PROJECT_ROOT:-./projects}/php:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    ports:
      - "${APACHE_PORT:-8080}:80"
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:php.localhost"
      - "traefik.port=80"

  react-dev:
    image: node:20-alpine
    container_name: react-dev
    working_dir: /app
    volumes:
      - ${PROJECT_ROOT:-./projects}/react:/app
    ports:
      - "${REACT_PORT:-3000}:3000"
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:react.localhost"
      - "traefik.port=3000"

  next-dev:
    image: node:20-alpine
    container_name: next-dev
    working_dir: /app
    volumes:
      - ${PROJECT_ROOT:-./projects}/next:/app
    ports:
      - "${NEXT_PORT:-3001}:3000"
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:next.localhost"
      - "traefik.port=3000"

  nuxt-dev:
    image: node:20-alpine
    container_name: nuxt-dev
    working_dir: /app
    volumes:
      - ${PROJECT_ROOT:-./projects}/nuxt:/app
    ports:
      - "${NUXT_PORT:-3002}:3000"
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:nuxt.localhost"
      - "traefik.port=3000"

  angular-dev:
    image: node:20-alpine
    container_name: angular-dev
    working_dir: /app
    volumes:
      - ${PROJECT_ROOT:-./projects}/angular:/app
    ports:
      - "${ANGULAR_PORT:-4200}:4200"
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:angular.localhost"
      - "traefik.port=4200"

  flutter-dev:
    image: cirrusci/flutter:stable
    container_name: flutter-dev
    working_dir: /app
    volumes:
      - ${PROJECT_ROOT:-./projects}/flutter:/app
    ports:
      - "${FLUTTER_PORT:-8090}:8090"
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:flutter.localhost"
      - "traefik.port=8090"

networks:
  backend:
    external: true

volumes:
  mariadb:
    driver: local
  postgres:
    driver: local
  gitlab_config:
    driver: local
  gitlab_logs:
    driver: local
  gitlab_data:
    driver: local
  portainer_data:
    driver: local
  grafana_data:
    driver: local