version: "3.3"
services:
    mariadb:
        container_name: mariadb
        restart: always
        image: arm64v8/mariadb:10.3
        environment:
            - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
            - MYSQL_DATABASE=${DATABASE_NAME}
        volumes:
            - mariadb:/var/lib/mysql
            - ./dumps:/dumps
        ports:
            - ${DATABASE_EXTERNAL_PORT}:3306
        labels:
            - "traefik.enable=false"
        networks:
            - backend

    postgres:
        container_name: postgres
        restart: always
        image: arm64v8/postgres:16.3-alpine
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_DATABASE_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DATABASE_NAME}
        volumes:
            - postgres:/var/lib/postgresql/data
            - ./dumps:/dumps
        ports:
            - ${POSTGRES_DATABASE_EXTERNAL_PORT}:5432
        labels:
            - "traefik.enable=false"
        networks:
            - backend

    redis:
        image: arm64v8/redis:5-alpine
        container_name: redis
        labels:
            - "traefik.enable=false"
        restart: always
        ports:
            - 6379:6379
        networks:
            - backend

    traefik:
        container_name: "traefik"
        image: "arm64v8/traefik:1.7.20"
        restart: "always"
        command: --api --docker=true
        ports:
            - "80:80"
            - "8080:8080"
            - "443:443"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - ./traefik:/etc/traefik
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=traefik"
            - "traefik.port=8080"
            - "traefik.backend=traefik"
            - "traefik.frontend.rule=Host:traefik.local"
        networks:
            - "backend"

    mailhog:
        image: "mailhog/mailhog:latest"
        container_name: "mailhog"
        restart: "always"
        networks:
            - "backend"
        labels:
            - "traefik.enable=true"
            - "traefik.frontend.rule=Host:mailhog.local"
            - "traefik.backend=mailhog"
            - "traefik.port=8025"
    
    phpmyadmin:
        image: arm64v8/phpmyadmin:latest
        restart: always
        volumes:
          - ./phpmyadmin.ini:/usr/local/etc/php/conf.d/phpmyadmin.ini
        networks:
          - backend
        environment:
          PMA_ARBITRARY: 1
          PMA_HOST: mariadb
          PMA_USER: root
          PMA_PASSWORD: root
          PMA_ABSOLUTE_URI: https://phpmyadmin.local
          UPLOAD_LIMIT: 512MB
        labels:
          - traefik.frontend.rule=Host:phpmyadmin.local
          - traefik.docker.network=backend
          - traefik.port=80

    pgadmin:
        image: dpage/pgadmin4:latest
        environment:
          PGADMIN_DEFAULT_EMAIL: admin@localhost
          PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            -"5050:80"
        networks:
            - backend
        labels:
            - traefik.frontend.rule=Host:pgadmin.localhost
            - traefik.port=80

    apache-php:
        image: arm64v8/php:${PHP_VERSION}-apache
        volumes:
            - ${PROJECT_ROOT}/php:/var/www/html
            - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
        ports:
            - "${APACHE_PORT}:80"
        networks:
            - backend
        environment:
            - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT}
            - PHP_MAX_EXECUTION_TIME=${PHP_MAX_EXECUTION_TIME}
        labels:
            - traefik.frontend.rule=Host:php.localhost
            - traefik.port=80

    nodejs:
        image: arm64v8/node:${NODE_VERSION}
        working_dir: /app
        volumes:
            - "${NODE_PORT}:3000"
        networks:
            - backend
        command: tail -f /dev/null
        labels:
            - traefik.frontend.rule=Host:node.localhost
            - traefik.port=3000


networks:
    backend:
        external: true

volumes:
    mariadb:
        driver: local
    postgres:
        driver: local
